### ISSUE TITLE
Narrator Tools Styles Incompatibility Issue

### ISSUE THREAD

**Issue by drywallmud** [FoxLee/fox-4e-styling#15]
![image](https://user-images.githubusercontent.com/5306827/219830745-14a9bef8-0112-453f-a372-d942b78a9665.png)

When the 4e styling is applied, the narrator description box in the chatlog is white text on white speech balloon background, which is not ideal. 
 
Narrator Tools module settings allows you to change the style of the narration overlay (text/shadows/background) but does not change the chatlog style, so this is not fixable from within settings as far as I am aware. I'm not sure how many people use both modules, but as the other module is system agnostic, I assume the change request to resolve this would be here. 
 
I totally understand that cross module compatibility is not guaranteed, but if this is something you'd wish to resolve, you'd never know without the report. Thanks again for an amazing styling module, our DMs cannot go back to default monster sheet styles.

**Comment by FoxLee** [comment]
Thanks for the report! As long as I'm not swamped with reports, I'm always happy to look at enabling specific compatibility (especially if it's just a bit of CSS, which is what this looks like).

I'll look at building in a fix for this before too long, but in the meanwhile you might find turning off the Extra Chat Styles (which is what causes the speech bubble style) makes it legible at least.

**Comment by FoxLee** [comment]
Okay! New version has a few tweaks that should make it play nice with Narrator Tools :}

I'd like to say I had some smart idea for making it work with unusual chat dialogues by default, but I don't—so I just put a clause on the CSS for the classes used by Narrator Styles, so it will avoid interfering with them. If you find any other cases where it seems to be changing things it shouldn't, do let me know :}

**Comment by drywallmud** [comment]
It works! I try to keep my modules to a minimum, but I definitely will report here if I see a chatlog styling issue with any others. Thanks so much for this, we're very reliant on both these modules!
