### ISSUE TITLE
French translation - Proposal

### ISSUE THREAD

**Issue by Gilphe** [FoxLee/fox-4e-styling#17]
Hi, 
I have used your module for some time now, and I really enjoy it. 
All of my players are french speaking, so I decided to translate your module to be more useful for all of them. 
So I would like to offer my translation to the community by adding it to your code.  I will follow future versions and add any terms that may be missing.
In the zip file I've attached, you will find : 
- fr.json : the french translation itself
- module.json : I've added the reference to the french, so it will be loaded automatically when people switch to "fr" in Foundry settings.

Regards,

[fr-translation.zip](https://github.com/FoxLee/fox-4e-styling/files/10908372/fr-translation.zip)

**Comment by FoxLee** [comment]
Thanks for your contribution! I'm very happy to add this :) You should see it in an update release shortly. I've also put you on the authors list, I hope that's okay!

**Comment by FoxLee** [comment]
Actually, your file made me notice something I missed adding an entry for. If you have a moment, could you let me know what the the French translation have for "Click to choose or change the portrait"?

Thanks again :)

**Comment by Gilphe** [comment]
Hi, 
The translation is this : "Cliquez pour sélectionner ou changer le portrait"

Thanks for adding my contribution, no problem to be mentionned in the authors list, it's kind of you.

**Comment by FoxLee** [comment]
That's fantastic. thank you :)
