### ISSUE TITLE
Roll table styling

### ISSUE THREAD

**Issue by drywallmud** [FoxLee/fox-4e-styling#20]
![image](https://user-images.githubusercontent.com/5306827/236114360-765bee6d-4e3d-40a5-9f5c-4ca6ef5fd7dd.png)

Roll tables are hard to read with the extra chat styling enabled. I could always disable extra chat styling, but I'd rather have both.

Once again, thanks for all your work!

**Comment by FoxLee** [comment]
Ah crap, I never use roll tables so I totally forgot to test them. Thank you, I'll check that out ASAP!

**Comment by FoxLee** [comment]
Fixed in v.0.9.46-beta. Thanks again!
