### ISSUE TITLE
Whisper Labels Could Use Contrast

### ISSUE THREAD

**Issue by drywallmud** [FoxLee/fox-4e-styling#21]
![image](https://github.com/FoxLee/fox-4e-styling/assets/5306827/8f849644-b021-4e0f-9ef4-3d7663a663e1)

Not a deal breaker, but its less than ideal, as it causes some confusion with whispers, especially with two whisperers at once keeping secrets. I figured you'd want to know.

Thanks again!

**Comment by FoxLee** [comment]
Fixed in release v0.9.47
