### ISSUE TITLE
Extra chat styles need backgrounds on ongoing damage updates in chat

### ISSUE THREAD

**Issue by drywallmud** [FoxLee/fox-4e-styling#22]
![image](https://github.com/FoxLee/fox-4e-styling/assets/5306827/d893a99a-e842-4fb4-aec2-f2efa5821a6f)

**Comment by FoxLee** [comment]
Whups, forgot this would be a things since it was already done in my local version ^^; Will have a new release shortly!

**Comment by FoxLee** [comment]
Fixed in 0.10.3-beta
