### ISSUE TITLE
Charts in the description window are now wonky

### ISSUE THREAD

**Issue by drywallmud** [FoxLee/fox-4e-styling#23]
Ypu probably know this, but in case you don't:
![image](https://github.com/FoxLee/fox-4e-styling/assets/5306827/fe09824c-a50a-4a87-bf82-18572ce1fef7)

Thanks again for this awesome application!

**Comment by FoxLee** [comment]
I did not! Thanks for flagging it. I'll check it out ASAP.

**Comment by FoxLee** [comment]
I've been unable to reproduce this in my local environment. Can you confirm that you have the most up-to-date version of the module?

Assuming yes, is this chat card one that was output to chat _before_ the most recent changes to either core or to my module? If so, do you see the same issue with a fresh chat output?

If you check all that and there's still a problem, that suggests there's some weird markup going on in your table. If possible, I'd like you to export the feature and send me the resulting JSON so I can investigate it directly!

**Comment by drywallmud** [comment]
Certainly!

0.10.4 (fairly certain it worked before the update)

`{"_id":"Pfjff7e5RfohkN6v","name":"Warlock's Curse","type":"power","img":"icons/magic/unholy/strike-hand-glow-pink.webp","effects":[{"icon":"systems/dnd4e/icons/statusEffects/curse.svg","origin":"Actor.rT50As2WX7pT9NTF.Item.Pfjff7e5RfohkN6v","flags":{"dnd4e":{"effectData":{"powerEffectTypes":"all","equippedRec":false,"durationType":"endOfEncounter","durationTurnInit":null,"startTurnInit":0},"dots":[]},"ActiveAuras":{"isAura":false,"aura":"None","radius":"","alignment":"","type":"","ignoreSelf":false,"height":false,"hidden":false,"displayTemp":false,"hostile":false,"onlyOnce":false,"nameOverride":"","customCheck":"","wallsBlock":"system"}},"duration":{"startTime":null,"seconds":null,"combat":null,"rounds":null,"turns":null,"startRound":15,"startTurn":null},"disabled":false,"name":"Cursed","transfer":false,"_id":"OkkWdunC4wZ7uu5t","changes":[],"description":"<p>This creature is cursed by Acadia until the end of the encounter or until it is reduced to 0 hit points or fewer.</p><p>When Acadia deals damage to a cursed enemy, he deals extra damage.</p>","statuses":[],"tint":"#f4dbff"}],"folder":null,"sort":0,"flags":{"autoanimations":{"id":"6a520dbc-f05d-461c-ab67-777535a42b6a","label":"Warlock's Curse","levels3d":{"type":"explosion","data":{"color01":"#FFFFFF","color02":"#FFFFFF","spritePath":"modules/levels-3d-preview/assets/particles/dust.png"},"sound":{"enable":false},"secondary":{"enable":false,"data":{"color01":"#FFFFFF","color02":"#FFFFFF","spritePath":"modules/levels-3d-preview/assets/particles/dust.png"}}},"macro":{"enable":false},"meleeSwitch":{"video":{"dbSection":"range","menuType":"weapon","animation":"arrow","variant":"regular","color":"regular"},"sound":{"enable":false,"delay":0,"repeat":1,"repeatDelay":250,"startTime":0,"volume":0.75},"options":{"detect":"automatic","range":2,"returning":false,"switchType":"on"}},"menu":"melee","primary":{"video":{"dbSection":"melee","menuType":"weapon","animation":"club","variant":"01","color":"white","enableCustom":false,"customPath":""},"sound":{"enable":false,"delay":0,"repeat":1,"repeatDelay":250,"startTime":0,"volume":0.75},"options":{"contrast":0,"delay":0,"elevation":1000,"isWait":false,"opacity":1,"playbackRate":1,"repeat":1,"repeatDelay":250,"saturate":0,"size":1,"tint":false,"tintColor":"#FFFFFF","zIndex":1}},"secondary":{"enable":false,"video":{"dbSection":"static","menuType":"spell","animation":"curewounds","variant":"01","color":"blue","enableCustom":false,"customPath":""},"sound":{"enable":false,"delay":0,"repeat":1,"repeatDelay":250,"startTime":0,"volume":0.75},"options":{"addTokenWidth":false,"anchor":"0.5","contrast":0,"delay":0,"elevation":1000,"fadeIn":250,"fadeOut":500,"isMasked":false,"isRadius":true,"isWait":false,"opacity":1,"repeat":1,"repeatDelay":250,"saturate":0,"size":1.5,"tint":false,"tintColor":"#FFFFFF","zIndex":1}},"soundOnly":{"sound":{"enable":false,"delay":0,"repeat":1,"repeatDelay":250,"startTime":0,"volume":0.75}},"source":{"enable":false,"video":{"dbSection":"static","menuType":"spell","animation":"curewounds","variant":"01","color":"blue","enableCustom":false,"customPath":""},"sound":{"enable":false,"delay":0,"repeat":1,"repeatDelay":250,"startTime":0,"volume":0.75},"options":{"addTokenWidth":false,"anchor":"0.5","contrast":0,"delay":0,"elevation":1000,"fadeIn":250,"fadeOut":500,"isMasked":false,"isRadius":false,"isWait":true,"opacity":1,"repeat":1,"repeatDelay":250,"saturate":0,"size":1,"tint":false,"tintColor":"#FFFFFF","zIndex":1}},"target":{"enable":false,"video":{"dbSection":"static","menuType":"spell","animation":"curewounds","variant":"01","color":"blue","enableCustom":false,"customPath":""},"sound":{"enable":false,"delay":0,"repeat":1,"repeatDelay":250,"startTime":0,"volume":0.75},"options":{"addTokenWidth":false,"anchor":"0.5","contrast":0,"delay":0,"elevation":1000,"fadeIn":250,"fadeOut":500,"isMasked":false,"isRadius":false,"opacity":1,"persistent":false,"repeat":1,"repeatDelay":250,"saturate":0,"size":1,"tint":false,"tintColor":"#FFFFFF","unbindAlpha":false,"unbindVisibility":false,"zIndex":1}},"isEnabled":true,"isCustomized":false,"fromAmmo":false,"version":5}},"system":{"description":{"value":"<p><strong>Feat Improved: Warlock's Wrath: </strong>You use d8s for your Warlock’s Curse damage.</p><p>Once per turn as a minor action, you can place a Warlock’s Curse on the enemy nearest to you that you can see. A cursed enemy is more vulnerable to your attacks. If you damage a cursed enemy, you deal extra damage. You decide whether to apply the extra damage after making the damage roll. You can deal this extra damage once per round.</p><p>A Warlock’s Curse remains in effect until the end of the encounter or until the cursed enemy drops to 0 hit points or fewer.</p><p>You can place a Warlock’s Curse on multiple targets over the course of an encounter; each curse requires the use of a minor action. You can’t place a Warlock’s Curse on a creature that is already affected by your or another character’s Warlock’s Curse.</p><p></p><table><tbody><tr><th><p><strong>Level</strong></p></th><th style=\"text-align: center; width: 72.9529%; height: 16px;\"><p><strong>Warlock's Curse Extra Damage</strong></p></th></tr><tr><td><p>1st - 10th</p></td><td><p>+[[/r 1d8[damage]#Warlock's Curse Extra Damage]]</p></td></tr><tr><td><p>11th - 20th</p></td><td><p>+[[/r 2d8[damage]#Warlock's Curse Extra Damage]]</p></td></tr><tr><td><p>21st - 30th</p></td><td><p>+[[/r 3d8[damage]#Warlock's Curse Extra Damage]]</p></td></tr></tbody></table>","chat":"","unidentified":""},"source":"Player's Handbook","activation":{"type":"","cost":0,"condition":""},"duration":{"value":null,"units":""},"target":"Nearest enemy you can see","range":{"value":null,"long":null,"units":""},"uses":{"value":0,"max":"0","per":""},"consume":{"type":"","target":"","amount":null},"macro":{"type":"script","scope":"global","launchOrder":"off","command":"","author":"","autoanimationHook":""},"attack":{"shareAttackRoll":false,"isAttack":false,"ability":"str","abilityBonus":0,"def":"ac","defBonus":0,"formula":"@wepAttack+@powerMod+@lvhalf","damageType":{},"effectType":{}},"hit":{"shareDamageRoll":false,"isDamage":true,"isHealing":false,"healSurge":"","baseQuantity":"@tier","baseDiceType":"d8","detail":"","formula":"@powBase","critFormula":"","healFormula":""},"miss":{"detail":"","formula":""},"effect":{"detail":""},"damage":{"parts":[],"versatile":""},"damageCrit":{"parts":[],"versatile":""},"damageImp":{"parts":[],"versatile":""},"damageCritImp":{"parts":[],"versatile":""},"keyWords":[""],"level":"1","powersource":"","secondPowersource":"","subName":"Warlock's Curse Power","prepared":true,"powerType":"class","powerSubtype":"attack","useType":"atwill","actionType":"minor","requirements":"","weaponType":"melee","weaponUse":"default","rangeType":"weapon","rangeTextShort":"","rangeText":"","rangePower":null,"area":0,"rechargeRoll":"","rechargeCondition":"","damageShare":false,"postEffect":true,"postSpecial":true,"autoGenChatPowerCard":false,"sustain":{"actionType":"none","detail":""},"trigger":"","requirement":"","special":"","specialAdd":{"parts":[]},"ability":null,"attackBonus":0,"chatFlavor":"","critical":null,"formula":"","save":{"ability":"","dc":null,"scaling":"spell"},"damageType":{"damage":false,"acid":false,"cold":false,"fire":false,"force":false,"lightning":false,"necrotic":false,"physical":false,"poison":false,"psychic":false,"radiant":false,"thunder":false},"effectType":{"beast":false,"beastForm":false,"charm":false,"conjuration":false,"fear":false,"healing":false,"illusion":false,"invigorating":false,"poison":false,"polymorph":false,"rage":false,"rattling":false,"reliable":false,"sleep":false,"spirit":false,"stance":false,"summoning":false,"teleportation":false,"zone":false,"augmentable":false,"aura":false,"channelDiv":false,"disease":false,"elemental":false,"enchantment":false,"evocation":false,"fullDis":false,"gaze":false,"mount":false,"necro":false,"nether":false,"runic":false,"transmutation":false},"effectHTML":false},"ownership":{"default":0,"wnfX3d13ou0DbHQ0":3},"_stats":{"systemId":"dnd4e","systemVersion":"0.4.27","coreVersion":"11.313","createdTime":1692931101467,"modifiedTime":1697596494267,"lastModifiedBy":"wnfX3d13ou0DbHQ0"}}`

**Comment by drywallmud** [comment]
This is the HTML: 

<p><strong>Feat Improved: Warlock's Wrath: </strong>You use d8s for your Warlock’s Curse damage.</p>
<p>Once per turn as a minor action, you can place a Warlock’s Curse on the enemy nearest to you that you can see. A cursed enemy is more vulnerable to your attacks. If you damage a cursed enemy, you deal extra damage. You decide whether to apply the extra damage after making the damage roll. You can deal this extra damage once per round.</p>
<p>A Warlock’s Curse remains in effect until the end of the encounter or until the cursed enemy drops to 0 hit points or fewer.</p>
<p>You can place a Warlock’s Curse on multiple targets over the course of an encounter; each curse requires the use of a minor action. You can’t place a Warlock’s Curse on a creature that is already affected by your or another character’s Warlock’s Curse.</p>
<p></p>
<table>
    <tbody><tr>
            <th>
                <p><strong>Level</strong></p>
            </th>
            <th style="text-align: center; width: 72.9529%; height: 16px;">
                <p><strong>Warlock's Curse Extra Damage</strong></p>
            </th>
</tr><tr>
            <td>
                <p>1st - 10th</p>
            </td>
            <td>
                <p>+[[/r 1d8[damage]#Warlock's Curse Extra Damage]]</p>
            </td>
</tr><tr>
            <td>
                <p>11th - 20th</p>
            </td>
            <td>
                <p>+[[/r 2d8[damage]#Warlock's Curse Extra Damage]]</p>
            </td>
</tr><tr>
            <td>
                <p>21st - 30th</p>
            </td>
            <td>
                <p>+[[/r 3d8[damage]#Warlock's Curse Extra Damage]]</p>
            </td>
</tr></tbody>
</table>

**Comment by drywallmud** [comment]
The issue is only in the chat output, it appears like this in the power window: 

![image](https://github.com/FoxLee/fox-4e-styling/assets/5306827/c88f44ab-4c34-4606-962c-5e9351685f7f)

**Comment by drywallmud** [comment]
It's only in the chat window, in the power window it appears fine:

![image](https://github.com/FoxLee/fox-4e-styling/assets/5306827/f670edb7-eba8-4800-9e72-533acaa67737)

**Comment by drywallmud** [comment]
And yes, its a fresh chat post.

**Comment by FoxLee** [comment]
Ah! Now I see why the main problem is happening. All the table cell content is inside paragraphs (which isn't normally what you would want for this sort of data) so it's inheriting the styling for that. I'll strip that styling from paragraphs that aren't immediate children of the card body, should take care of it.

(Incidentally, if you want the blue header row on your tables, pop your header row in a `<thead>` section instead of in the `<tbody>`. The editor doesn't use the best markup for this (alas, WYSIWYG editor things) but you can tweak it manually if you want the proper styling!)

That said, I still can't get _exactly_ the same result as you, with the alternating table rows also transparent. Possibly I had already fixed it locally? I thought your bug was filed before I had done any additional work, but maybe not. In any case, grab the incoming update (should be in just a few minutes) and let me know if that does the trick!

**Comment by drywallmud** [comment]
Fixed on update!

Thanks so much! I will also use your styling advice with <thead> from now on.

[image](https://github.com/FoxLee/fox-4e-styling/assets/5306827/0722430e-80c9-4e5b-a1a6-d0664d863cda)
