### ISSUE TITLE
Styling fix required after latest update (v0.4.44)

### ISSUE THREAD

**Issue by drywallmud** [FoxLee/fox-4e-styling#24]
Not sure if you're aware, please see: [https://github.com/EndlesNights/dnd4eBeta/issues/348]

![image](https://github.com/FoxLee/fox-4e-styling/assets/5306827/d689bcc2-116c-4b81-9a38-0fc6e7c368bd)

**Comment by FoxLee** [comment]
Ah yes, I knew this was coming when the dev system branch turned into the current branch. Just didn't realise it was going to be today <XD I'll take care of when I get home from work tonight—but for anybody needing to run in the mean time, you should have no issues if you temporarily revert to the default sheets/styling.

**Comment by FoxLee** [comment]
Fixed!
