### ISSUE TITLE
Did I update to v12 too soon or is this just me?

### ISSUE THREAD

**Issue by drywallmud** [FoxLee/fox-4e-styling#27]
My apologies if I jumped the gun:

![image](https://github.com/FoxLee/fox-4e-styling/assets/5306827/b7f52f64-a05a-48b3-8261-d203907c304d)

**Comment by FoxLee** [comment]
Correct, the module is only compatible with v11 for now. (The compatibility
info should show this—let me know if it appears to be set incorrectly.)

**Comment by drywallmud** [comment]
No, I should have checked, it's orange. This was my bad. We had a lot of region-based stuff coming around the corner and I got a bit too eager. 

Sorry for reporting erroneously!

**Comment by drywallmud** [comment]
Any ETA on v12 compatibility?

**Comment by FoxLee** [comment]
FINALLY done! Thanks for your patience!

**Comment by drywallmud** [comment]
The thanks belongs all to you! It works amazing now!
