### ISSUE TITLE
<b> now renders as italics instead of bold in NPC powers

### ISSUE THREAD

**Issue by WilliamTDoran** [FoxLee/fox-4e-styling#28]
As the title said, after the newest update if you have any in-line \<b> tags in a power, when the power card is pushed to chat, it renders as italics. It still renders correctly as bold in the character sheet.

**Comment by FoxLee** [comment]
I'll look into this—it's probably based on the system output using the
outdated <b> tag and me assuming it was safe to target since it's obsolete.
In the mean time, as a workaround you can use <strong>, which is the
contemporary replacement for <b>.

**Comment by FoxLee** [comment]
Fixed in release 1.0.1! Thanks for your patience :}

(You really should use `strong` though! Various hacks like fontawesome use obsolete tags because they shouldn't normally appear, so using them is likely to get you in trouble.)

**Comment by WilliamTDoran** [comment]
> Fixed in release 1.0.1! Thanks for your patience :}
> 
> (You really should use `strong` though! Various hacks like fontawesome use obsolete tags because they shouldn't normally appear, so using them is likely to get you in trouble.)

Yeah, my concern was more about having to go through every one of the hundreds of powers I've already made and change it; I've started using strong going forward
